### ISSUE TITLE
problems when I run the road-net demo

### ISSUE THREAD

**Issue by jiangfeng15** [e-lab/torch7-demos#5]
@andreydung, I have the same question when I run the road-net demo
but how to solve it?
==> processing options
multinet-float-ascii.net
qlua: cannot open <multinet-float-ascii.net> in mode r 
stack traceback:
	[C]: at 0x7fc57473a960
	[C]: at 0x7fc5485da330
	[C]: in function 'DiskFile'
	/usr/local/share/lua/5.1/torch/File.lua:292: in function 'load'
	run.lua:72: in function 'init_net'
	run.lua:241: in main chunk

**Comment by Aysegul** [comment]
fixed in the commit dcb0fdf5da829fa1326202400fc73027fddd5c15 
Thanks for reporting, btw the default option is camera but you can give a video of a road for more meaningful output by
```bashrc
 qlua run.lua -v 'video_path' 
```
