### ISSUE TITLE
facedetector demo does not work.

### ISSUE THREAD

**Issue by xumbu** [e-lab/torch7-demos#6]
I tried to run your facedetector demo: https://github.com/e-lab/torch7-demos/tree/master/face-detector-elab on Ubuntu (15.04).

Unfortunately I got following output:

>  nico@ubuntuServer:~/torchprojects/face-dector-elab$ sudo qlua run.lua
> ==> processing options
> Neural Network used: 
>     nn.Sequential {
>   [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> output](1): nn.SpatialConvolutionMM
>   (2): nn.Threshold
>   (3): nn.SpatialMaxPooling
>   (4): nn.SpatialConvolutionMM
>   (5): nn.Threshold
>   (6): nn.SpatialClassifier
> }
> Initializing device: /dev/video0
> FPS wanted 1 
> Using 1 buffers
> Warning: camera resolution changed to 480x640
> camera[0] started : 1
> /usr/local/share/lua/5.1/nn/Sequential.lua:29: bad argument #1 (field dW does not exist)
> stack traceback:
>     [C]: in function 'updateOutput'
>     /usr/local/share/lua/5.1/nn/Sequential.lua:29: in function 'forward'
>     run.lua:138: in function 'process'
>     run.lua:191: in function run.lua:188

on another ubuntu machine (14.04) there is another error message:

> ==> processing options
> qlua: /root/torch/install/share/lua/5.1/torch/File.lua:255: read error: read 1 blocks instead of 25602 at /root/torch/pkg/torch/lib/TH/THDiskFile.c:310
> stack traceback:
>     [C]: at 0x7ffd28cfd970
>     [C]: in function 'read'
>     /root/torch/install/share/lua/5.1/torch/File.lua:255: in function </root/torch/install/share/lua/5.1/torch/File.lua:185>
>     [C]: in function 'read'

**Comment by Jennyhuo** [comment]
I tried to run your facedetector demo: https://github.com/e-lab/torch7-demos/tree/master/face-detector-elab on Ubuntu (15.04).
Unfortunately I got following output:
qlua: .../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:98: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
	[C]: at 0x7ffbbbb32930
	[C]: in function 'format'
	.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:98: in function <.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:94>
	[C]: in function 'tostring'
	/home/jenny/torch/install/share/lua/5.1/nn/Sequential.lua:118: in function </home/jenny/torch/install/share/lua/5.1/nn/Sequential.lua:107>
	[C]: at 0x7ffb8b3b1760
	[C]: in function 'print'
	run.lua:83: in main chunk

**Comment by hdmetor** [comment]
I have a similar problem on Mac (and I suspect that the network is not being properly loaded):

    $qlua run.lua

    ==> processing options
    Neural Network used:
    qlua: .../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:98: bad argument #2 to 'format' (number expected, got nil)
    stack traceback:
        [C]: at 0x010c1c22b0
        [C]: in function 'format'
        .../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:98: in function <.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:94>
        [C]: in function 'tostring'
        /path/to/torch/install/share/lua/5.1/nn/Sequential.lua:118: in function </path/to/torch/install/share/lua/5.1/nn/Sequential.lua:107>
        [C]: at 0x175ad610
        [C]: in function 'print'

**Comment by zunware** [comment]
Me too: 

```
==> processing options
Neural Network used: 
qlua: .../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:98: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
	[C]: at 0x010c193e90
	[C]: in function 'format'
	.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:98: in function <.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:94>
	[C]: in function 'tostring'
	/Users/pp/torch/install/share/lua/5.1/nn/Sequential.lua:118: in function </Users/pp/torch/install/share/lua/5.1/nn/Sequential.lua:107>
	[C]: at 0x177e0610
	[C]: in function 'print'
	run.lua:83: in main chunk

```

**Comment by psadil** [comment]
Many hours were spent working on this (admittedly, I'm pretty fresh to torch)...ended up eventually finding a [useful thread](https://groups.google.com/forum/#!searchin/torch7/face-detector/torch7/p6k2RW1-Ptw/HF0ReyumAQAJ) from the google group. In case anyone else finds this lonely repository in the future...
